language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_c89fc487395c_key -iv $encrypted_c89fc487395c_iv -in application.properties.enc -out src/main/resources/application.properties -d

