language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_37c734d3f559_key -iv $encrypted_37c734d3f559_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
env:
  global:
    secure: t6AeZDvmneB1Mqk9SjxN2CgpRL6ZtLrHXCPvqKca8Hdc44rfKaTIFhN3kSQ4ZV1tk3fC1BzUDJ1+bvjZlPITvS6tcj57Fj9J6QnrYX8iAqW/dJdCxWqueDUJ9jF0qXlw4DbIGkHydKkyPhWTdkkG+TcKihSjZgRD6pqL1OTJe02gmo4kFrG86ekmG+soq4f1oRt2cDpQl+g+pHMLLxjwPOmkC6ebJJgfmw9UdCpA5vBFr7/Uegb7M1dB0XmZQC6lz3Om+SdrAfPQiRYBcvmCS4bqHRXSMrzYBUaz1A5IwsuhG2Fs9jc4nWvX15wKWFBPWHZD1AR4X/x3pZ47mqFzxL5h2m7i0VSy2bFvpj94j3/dV6fWK9Wi7xqfIiGPfFLMm36j0kJrN/RzvziCeC8719xdq/dHKvdvLBJkF7FbJt8WcRbvvBz0lYsBgd6zn/mXKCXCpnTJZaTrneOQ2BQMH2qM5CcmKGcpnCzCyAa8OdNX8IrYLAgqgb+1Ta+dr8kui7CuvU1lh6QJiwQIxlBqtXOifQtF4h1DRJo8kkvGNtp4AclJL0whB9ywUkUsyU44aMNLvieR1JD5CwJ0vUdxQzmOn/B8z6QYrQD59nIqKcQR16mKkwwL1/O5KiSGTWPkhVjTCoJImie6NwdcV+gPE9uhBSS0DhHIzRocVya1Hsc=
dd:
- openssl aes-256-cbc -K $encrypted_e8d709e1cfb8_key -iv $encrypted_e8d709e1cfb8_iv
  -in application.properties.enc -out application.properties -d
